// Every user-visible Polish string of the showroom lives in this file.
// No other file contains a Polish string literal.

const number = new Intl.NumberFormat("pl-PL", { maximumFractionDigits: 2 });
const unknownFact = "Brak potwierdzonych danych";

export const copy = {
  showroomTitle: "Wirtualny salon samochodów",
  unknownFact,
  unconfirmedFact: "Dane niepotwierdzone",
  confirmedAbsent: "Potwierdzony brak",
  unconfirmedValue: (value: string) => `${value} · dane niepotwierdzone`,
  modelCounter: (position: number, total: number) => `${position} z ${total}`,
  previousModel: "Poprzedni model",
  nextModel: "Następny model",
  versions: "Wersje",
  selectVersion: (name: string) => `Wybierz wersję ${name}`,
  previewImage: (name: string) => `${name}. Zdjęcie poglądowe`,
  previewLabel: "Zdjęcie poglądowe",
  power: "Moc",
  consumption: "Spalanie",
  dimensions: "Wymiary",
  weight: "Masa",
  cabinNoise: "Hałas w kabinie",
  offers: "Oferty",
  financing: "Finansowanie",
  warranty: "Gwarancja",
  more: "Więcej",
  back: "Wróć",
  selectedVersion: "Wybrana wersja",
  availableOffer: "Oferta dostępna",
  pendingOffer: "Oferta oczekuje na potwierdzenie",
  noOffer: "Brak oferty",
  noConfirmedPrice: "Brak potwierdzonej ceny",
  price: "Cena",
  specialPrice: "Cena specjalna",
  catalogPrice: "Cena katalogowa",
  configurationPrice: "Cena konfiguracji",
  priceBeforeDiscount: "Cena przed rabatem",
  discount: "Rabat",
  priceAfterDiscount: "Cena po rabacie",
  availableFinancing: "Finansowanie dostępne",
  pendingFinancing: "Finansowanie oczekuje na potwierdzenie",
  noFinancing: "Brak oferty finansowania",
  noFinancingTerms: "Brak potwierdzonych warunków finansowania",
  financingVariant: (position: number) => `Wariant ${position}`,
  basePrice: "Cena bazowa",
  duration: "Okres",
  initialPayment: "Wpłata początkowa",
  installment: "Rata",
  nominalInterestRate: "Oprocentowanie nominalne",
  annualPercentageRate: "RRSO",
  baseWarranty: "Gwarancja podstawowa",
  warrantyExtensions: "Rozszerzenia gwarancji",
  noBaseWarranty: "Brak potwierdzonej gwarancji podstawowej",
  noWarrantyExtensions: "Brak potwierdzonych rozszerzeń gwarancji",
  distanceLimit: "Limit przebiegu",
  warrantyTerms: "Warunki",
  noMileageLimit: "Bez limitu kilometrów",
  youtube: "YouTube",
  technicalData: "Dane techniczne",
  noYoutube: "Brak materiałów YouTube",
  noTechnicalData: "Brak materiałów technicznych",
  sourceUnavailable: "Brak potwierdzonego źródła",
  source: (label: string, accessedAt: string) =>
    `Źródło: ${label} · dostęp: ${accessedAt}`,
  pln: (value: number) => `${number.format(value)} zł`,
  percent: (value: number) => `${number.format(value)}%`,
  months: (value: number) => `${number.format(value)} mies.`,
  years: (value: number) => `${number.format(value)} lat`,
  kilometers: (value: number) => `${number.format(value)} km`,
  fuelLabels: {
    petrol: "benzyna",
    lpg: "LPG",
    hybrid: "hybryda",
    electric: "napęd elektryczny",
    unknown: unknownFact,
  },
} as const;
